### PR TITLE
Don't send HSTS headers over non-HTTPS connections

### LINKED ISSUE #5: Don't send HSTS headers over non-HTTPS connections
From the Wikipedia page on HSTS:

> _"Strict-Transport-Security headers must be sent via HTTPS responses only. Client implementations must not respect STS headers sent over non-HTTPS responses, or over HTTPS responses which are not using properly configured, trusted certificates. The following server configuration snippets should be within the context of an SSL site configuration block, and the code examples are intended to be within the context of HTTPS responses only."_

So https://github.com/kennethreitz/flask-sslify/blob/6735984ce259aee0d042c9e36d5d79040ccd0319/flask_sslify.py#L54 should be returning HSTS-headers only for HTTPS responses.

I'm not sure what's the best criterium to decide whether the current response is secure in Flask, though. Ideas?

### PR DESCRIPTION
**Pull request by nvie**
This fixes #5.

### CODE REVIEW

**Comment by kennethreitz** [comment]
Thanks!

**Comment by kennethreitz** [comment]
Hmm, does it hurt to send them over regular connections?

**Comment by nvie** [comment]
Well, I suppose it doesn't _hurt_, no. But from the specs:

> _"Client implementations must not respect STS headers sent over non-HTTPS responses […]"_

So it might be confusing to send them over non-secure connections. This is a bit more restricting, adding the header only to connections where it actually makes sense.

**Comment by jparise** [comment]
I'd actually go even further and apply the same criteria (e.g. non-debug mode) that the redirection code uses.

**Comment by kennethreitz** [comment]
Man, I have no idea why I didn't merge this.

**Comment by nvie** [comment]
LOL, :sparkles: :cake: :sparkles: anyway :)

**Pull request merged**
