### PR TITLE
Add option to SSLify when debug is enabled, too.

### PR DESCRIPTION
**Pull request by rosensama**

### CODE REVIEW

**Comment by josegonzalez** [comment]
👍

**Comment by stevewilhelm** [comment]
FYI. documentation calls the option debug_ssl, code defines it as ssl_debug.

**Comment by Projjol-zz** [comment]
@rosensama if you can update the PR by resolving existing conflicts I'll be happy to check and merge 👍

**Comment by rosensama** [comment]
Looks like that should be easy enough, but the README says it's no longer
maintained, so how does the PR help?

**Comment by timofurrer** [comment]
@rosensama are you still using flask-sslify? 
Can you switch to https://github.com/GoogleCloudPlatform/flask-talisman ?

**Comment by rosensama** [comment]
@timofurrer correct, I no longer use flask-sslify.   Was just responding to @Projjol's request.

**Comment by timofurrer** [comment]
Yeah, that's absolutely, fine. I was just curious. 
So, I think I'm going to close this PR (even though it's fully legit ;)) and see if I can archive this repository.

Thanks 🎉

**Pull request closed without merging**
